import type { BotAgent, StartNodeConfig, MessageNodeConfig, QuestionNodeConfig, ConditionNodeConfig, AiExtractNodeConfig, CrmActionNodeConfig, HumanHandoffNodeConfig } from './types';

export const MOCK_AGENTS: BotAgent[] = [
  {
    id: 'bot-1',
    name: 'Activación Bono Taxi',
    description: 'Flujo de activación de bono para conductores de taxi',
    status: 'active',
    channel: 'whatsapp',
    brainMode: 'flow_with_ai',
    activeConversations: 24,
    totalConversations: 156,
    conversionRate: 68,
    handoffRate: 12,
    lastUpdated: '2026-05-28T10:30:00Z',
    createdAt: '2026-04-15T08:00:00Z',
    flow: {
      id: 'flow-1',
      name: 'Activación Bono Taxi',
      description: 'Flujo de activación de bono para conductores de taxi',
      status: 'active',
      nodes: [
        { id: 'n-1', type: 'start', position: { x: 80, y: 220 }, data: { nodeType: 'start', label: 'Inicio', enabled: true, config: { name: 'Inicio', description: 'Inicio del flujo de activación' } as StartNodeConfig } },
        { id: 'n-2', type: 'message', position: { x: 380, y: 220 }, data: { nodeType: 'message', label: 'Bienvenida', enabled: true, config: { text: '¡Hola {{nombre}}! Somos Taxi Monterrico. ¿Te gustaría activar tu bono de bienvenida?', attachments: [], delay: 0 } as MessageNodeConfig } },
        { id: 'n-3', type: 'question', position: { x: 680, y: 220 }, data: { nodeType: 'question', label: '¿Interesado?', enabled: true, config: { text: '¿Estás interesado en activar tu bono?', field_key: 'interesado', field_type: 'boolean', use_ai_extraction: false, extraction_schema: '', fallback_message: 'Por favor responde sí o no.', max_attempts: 2 } as QuestionNodeConfig } },
        { id: 'n-4', type: 'condition', position: { x: 980, y: 220 }, data: { nodeType: 'condition', label: '¿Respuesta?', enabled: true, config: { rules: [{ id: 'r1', operator: 'equals', field_key: 'interesado', value: 'sí', output_label: 'Sí' }, { id: 'r2', operator: 'equals', field_key: 'interesado', value: 'no', output_label: 'No' }] } as ConditionNodeConfig } },
        { id: 'n-5', type: 'message', position: { x: 1280, y: 120 }, data: { nodeType: 'message', label: 'Pasos a seguir', enabled: true, config: { text: 'Genial! Para activar tu bono necesito algunos datos:\n1. Documento de identidad\n2. Placa del vehículo\n3. Foto de tu DNI', attachments: [], delay: 0 } as MessageNodeConfig } },
        { id: 'n-6', type: 'question', position: { x: 1280, y: 300 }, data: { nodeType: 'question', label: 'Docs listos?', enabled: true, config: { text: '¿Tienes tus documentos listos?', field_key: 'docs_listos', field_type: 'boolean', use_ai_extraction: false, extraction_schema: '', fallback_message: 'Responde sí o no.', max_attempts: 3 } as QuestionNodeConfig } },
        { id: 'n-7', type: 'crm_action', position: { x: 1580, y: 120 }, data: { nodeType: 'crm_action', label: 'Crear tarea', enabled: true, config: { action_type: 'add_tag', payload: '{"tag":"bono_interesado"}' } as CrmActionNodeConfig } },
        { id: 'n-8', type: 'human_handoff', position: { x: 1580, y: 300 }, data: { nodeType: 'human_handoff', label: 'Derivar a humano', enabled: true, config: { message: 'Te contactaremos pronto para ayudarte.', queue: 'bonos', operator: '', tag: 'bono_pendiente' } as HumanHandoffNodeConfig } },
        { id: 'n-9', type: 'message', position: { x: 1280, y: 480 }, data: { nodeType: 'message', label: 'Despedida', enabled: true, config: { text: 'Entendido. Si cambias de opinión, estaremos aquí.', attachments: [], delay: 0 } as MessageNodeConfig } },
        { id: 'n-10', type: 'end', position: { x: 1280, y: 640 }, data: { nodeType: 'end', label: 'Fin', enabled: true, config: { message: 'Gracias por tu tiempo.', session_status: 'completed' } as any } },
      ],
      edges: [
        { id: 'e-1', source: 'n-1', target: 'n-2', condition_type: 'always', condition_config: {} },
        { id: 'e-2', source: 'n-2', target: 'n-3', condition_type: 'always', condition_config: {} },
        { id: 'e-3', source: 'n-3', target: 'n-4', condition_type: 'always', condition_config: {} },
        { id: 'e-4', source: 'n-4', target: 'n-5', condition_type: 'conditional', condition_config: { rule_id: 'r1' }, label: 'Sí' },
        { id: 'e-5', source: 'n-5', target: 'n-6', condition_type: 'always', condition_config: {} },
        { id: 'e-6', source: 'n-4', target: 'n-9', condition_type: 'conditional', condition_config: { rule_id: 'r2' }, label: 'No' },
        { id: 'e-7', source: 'n-6', target: 'n-7', condition_type: 'conditional', condition_config: { rule_id: 'r1' }, label: 'Sí' },
        { id: 'e-8', source: 'n-7', target: 'n-10', condition_type: 'always', condition_config: {} },
        { id: 'e-9', source: 'n-6', target: 'n-8', condition_type: 'conditional', condition_config: { rule_id: 'r2' }, label: 'No' },
        { id: 'e-10', source: 'n-8', target: 'n-10', condition_type: 'always', condition_config: {} },
        { id: 'e-11', source: 'n-9', target: 'n-10', condition_type: 'always', condition_config: {} },
      ],
    },
  },
  {
    id: 'bot-2',
    name: 'Calificación de Leads',
    description: 'Evalúa y califica leads automáticamente según sus respuestas',
    status: 'active',
    channel: 'webchat',
    brainMode: 'flow_only',
    activeConversations: 8,
    totalConversations: 89,
    conversionRate: 45,
    handoffRate: 25,
    lastUpdated: '2026-05-27T14:00:00Z',
    createdAt: '2026-03-20T10:00:00Z',
    flow: {
      id: 'flow-2',
      name: 'Calificación de Leads',
      description: 'Evalúa y califica leads automáticamente según sus respuestas',
      status: 'active',
      nodes: [
        { id: 'n-1', type: 'start', position: { x: 80, y: 220 }, data: { nodeType: 'start', label: 'Inicio', enabled: true, config: { name: 'Inicio', description: '' } as StartNodeConfig } },
        { id: 'n-2', type: 'message', position: { x: 380, y: 220 }, data: { nodeType: 'message', label: 'Bienvenida lead', enabled: true, config: { text: 'Gracias por tu interés. Vamos a hacerte algunas preguntas.', attachments: [], delay: 0 } as MessageNodeConfig } },
        { id: 'n-3', type: 'question', position: { x: 680, y: 220 }, data: { nodeType: 'question', label: '¿Presupuesto?', enabled: true, config: { text: '¿Cuál es tu presupuesto aproximado?', field_key: 'presupuesto', field_type: 'text', use_ai_extraction: true, extraction_schema: '{"type":"object","properties":{"monto":{"type":"number"}}}', fallback_message: 'Indícanos un monto aproximado.', max_attempts: 2 } as QuestionNodeConfig } },
        { id: 'n-4', type: 'condition', position: { x: 980, y: 220 }, data: { nodeType: 'condition', label: 'Presupuesto alto?', enabled: true, config: { rules: [{ id: 'r1', operator: 'greater_than', field_key: 'monto', value: '5000', output_label: 'Alto' }, { id: 'r2', operator: 'exists', field_key: 'monto', value: '', output_label: 'Bajo' }] } as ConditionNodeConfig } },
        { id: 'n-5', type: 'crm_action', position: { x: 1280, y: 120 }, data: { nodeType: 'crm_action', label: 'Lead calificado', enabled: true, config: { action_type: 'add_tag', payload: '{"tag":"lead_calificado"}' } as CrmActionNodeConfig } },
        { id: 'n-6', type: 'human_handoff', position: { x: 1280, y: 360 }, data: { nodeType: 'human_handoff', label: 'Derivar', enabled: true, config: { message: 'Un asesor te contactará pronto.', queue: 'ventas', operator: '', tag: 'lead_interesado' } as HumanHandoffNodeConfig } },
        { id: 'n-7', type: 'end', position: { x: 1280, y: 540 }, data: { nodeType: 'end', label: 'Fin', enabled: true, config: { message: '', session_status: 'completed' } as any } },
      ],
      edges: [
        { id: 'e-1', source: 'n-1', target: 'n-2', condition_type: 'always', condition_config: {} },
        { id: 'e-2', source: 'n-2', target: 'n-3', condition_type: 'always', condition_config: {} },
        { id: 'e-3', source: 'n-3', target: 'n-4', condition_type: 'always', condition_config: {} },
        { id: 'e-4', source: 'n-4', target: 'n-5', condition_type: 'conditional', condition_config: { rule_id: 'r1' }, label: 'Alto' },
        { id: 'e-5', source: 'n-5', target: 'n-7', condition_type: 'always', condition_config: {} },
        { id: 'e-6', source: 'n-4', target: 'n-6', condition_type: 'conditional', condition_config: { rule_id: 'r2' }, label: 'Bajo' },
        { id: 'e-7', source: 'n-6', target: 'n-7', condition_type: 'always', condition_config: {} },
      ],
    },
  },
  {
    id: 'bot-3',
    name: 'FAQ Automático',
    description: 'Responde preguntas frecuentes sobre requisitos y documentación',
    status: 'paused',
    channel: 'all',
    brainMode: 'flow_with_ai',
    activeConversations: 0,
    totalConversations: 312,
    conversionRate: 82,
    handoffRate: 8,
    lastUpdated: '2026-05-20T09:00:00Z',
    createdAt: '2026-02-01T08:00:00Z',
    flow: {
      id: 'flow-3',
      name: 'FAQ Automático',
      description: 'Responde preguntas frecuentes sobre requisitos y documentación',
      status: 'active',
      nodes: [
        { id: 'n-1', type: 'start', position: { x: 80, y: 220 }, data: { nodeType: 'start', label: 'Inicio FAQ', enabled: true, config: { name: 'Inicio', description: '' } as StartNodeConfig } },
        { id: 'n-2', type: 'ai_extract', position: { x: 380, y: 220 }, data: { nodeType: 'ai_extract', label: 'Clasificar consulta', enabled: true, config: { prompt: 'Clasifica la consulta del usuario en: requisitos, documentos, horarios, pagos, otros', schema: '{"type":"object","properties":{"categoria":{"type":"string"},"consulta":{"type":"string"}}}', min_confidence: 0.7, fallback_message: 'No entendí tu consulta.' } as AiExtractNodeConfig } },
        { id: 'n-3', type: 'condition', position: { x: 680, y: 220 }, data: { nodeType: 'condition', label: '¿Categoría?', enabled: true, config: { rules: [{ id: 'r1', operator: 'equals', field_key: 'categoria', value: 'requisitos', output_label: 'Req' }, { id: 'r2', operator: 'equals', field_key: 'categoria', value: 'documentos', output_label: 'Docs' }, { id: 'r3', operator: 'exists', field_key: 'categoria', value: '', output_label: 'Otros' }] } as ConditionNodeConfig } },
        { id: 'n-4', type: 'message', position: { x: 980, y: 60 }, data: { nodeType: 'message', label: 'Requisitos', enabled: true, config: { text: 'Los requisitos son:\n- DNI vigente\n- Licencia de conducir\n- Tarjeta de propiedad\n- Recibo de luz', attachments: [], delay: 0 } as MessageNodeConfig } },
        { id: 'n-5', type: 'message', position: { x: 980, y: 220 }, data: { nodeType: 'message', label: 'Documentos', enabled: true, config: { text: 'Puedes enviar tus documentos en formato PDF o foto.', attachments: [], delay: 0 } as MessageNodeConfig } },
        { id: 'n-6', type: 'human_handoff', position: { x: 980, y: 380 }, data: { nodeType: 'human_handoff', label: 'Derivar', enabled: true, config: { message: 'Te conectamos con un asesor.', queue: 'soporte', operator: '', tag: 'consulta_faq' } as HumanHandoffNodeConfig } },
        { id: 'n-7', type: 'end', position: { x: 1280, y: 220 }, data: { nodeType: 'end', label: 'Fin FAQ', enabled: true, config: { message: '¿Necesitas algo más?', session_status: 'completed' } as any } },
      ],
      edges: [
        { id: 'e-1', source: 'n-1', target: 'n-2', condition_type: 'always', condition_config: {} },
        { id: 'e-2', source: 'n-2', target: 'n-3', condition_type: 'always', condition_config: {} },
        { id: 'e-3', source: 'n-3', target: 'n-4', condition_type: 'conditional', condition_config: { rule_id: 'r1' }, label: 'Req' },
        { id: 'e-4', source: 'n-4', target: 'n-7', condition_type: 'always', condition_config: {} },
        { id: 'e-5', source: 'n-3', target: 'n-5', condition_type: 'conditional', condition_config: { rule_id: 'r2' }, label: 'Docs' },
        { id: 'e-6', source: 'n-5', target: 'n-7', condition_type: 'always', condition_config: {} },
        { id: 'e-7', source: 'n-3', target: 'n-6', condition_type: 'conditional', condition_config: { rule_id: 'r3' }, label: 'Otros' },
        { id: 'e-8', source: 'n-6', target: 'n-7', condition_type: 'always', condition_config: {} },
      ],
    },
  },
  {
    id: 'bot-4',
    name: 'Recordatorio de Cita',
    description: 'Envía recordatorios de citas y confirma asistencia',
    status: 'draft',
    channel: 'whatsapp',
    brainMode: 'flow_only',
    activeConversations: 0,
    totalConversations: 0,
    conversionRate: 0,
    handoffRate: 0,
    lastUpdated: '2026-05-25T16:00:00Z',
    createdAt: '2026-05-25T16:00:00Z',
    flow: {
      id: 'flow-4',
      name: 'Recordatorio de Cita',
      description: 'Envía recordatorios de citas y confirma asistencia',
      status: 'draft',
      nodes: [
        { id: 'n-1', type: 'start', position: { x: 80, y: 220 }, data: { nodeType: 'start', label: 'Inicio', enabled: true, config: { name: 'Inicio', description: '' } as StartNodeConfig } },
        { id: 'n-2', type: 'message', position: { x: 380, y: 220 }, data: { nodeType: 'message', label: 'Recordatorio', enabled: true, config: { text: 'Hola {{nombre}}, te recordamos que tienes una cita el día {{fecha_cita}}.', attachments: [], delay: 0 } as MessageNodeConfig } },
        { id: 'n-3', type: 'end', position: { x: 680, y: 220 }, data: { nodeType: 'end', label: 'Fin', enabled: true, config: { message: 'Gracias por confirmar.', session_status: 'completed' } as any } },
      ],
      edges: [
        { id: 'e-1', source: 'n-1', target: 'n-2', condition_type: 'always', condition_config: {} },
        { id: 'e-2', source: 'n-2', target: 'n-3', condition_type: 'always', condition_config: {} },
      ],
    },
  },
];
