import type { HotProspectsSummary } from '@/lib/analyticsApi';

export type HotProspectSparkline = {
  data: number[];
  color: string;
  variant?: 'bar' | 'area';
};

/** Datos de ejemplo hasta validar el endpoint `hotProspects` en reportes. */
export const MOCK_HOT_PROSPECTS_SPARKLINES: Record<
  'total' | 'pipeline' | 'cierre' | 'activos',
  HotProspectSparkline
> = {
  total: {
    data: [28, 31, 33, 35, 38, 40, 42],
    color: '#f97316',
    variant: 'area',
  },
  pipeline: {
    data: [820, 910, 980, 1050, 1120, 1180, 1245],
    color: '#ef4444',
    variant: 'area',
  },
  cierre: {
    data: [4, 5, 5, 6, 7, 7, 8],
    color: '#22c55e',
    variant: 'bar',
  },
  activos: {
    data: [5, 6, 6, 7, 8, 8, 9],
    color: '#15803d',
    variant: 'bar',
  },
};

/** Datos de ejemplo hasta validar el endpoint `hotProspects` en reportes. */
export const MOCK_HOT_PROSPECTS_SUMMARY: HotProspectsSummary = {
  week: {
    name: 'W28',
    weekStart: '2026-07-07T05:00:00.000Z',
    weekEnd: '2026-07-14T04:59:59.999Z',
  },
  totalCalientes: 42,
  pipelineCaliente: 1_245_000,
  enCierre: 8,
  yaActivos: 9,
  topProspects: [
    {
      id: 'mock-hot-1',
      urlSlug: 'southern-copper-premium',
      name: 'Southern Copper Premium',
      etapa: 'negociacion',
      etapaLabel: 'Negociación',
      probability: 70,
      assignedToName: 'María García',
      facturacionEstimada: 150_000,
    },
    {
      id: 'mock-hot-2',
      urlSlug: 'repsol-corporate-fleet',
      name: 'Repsol Corporate Fleet',
      etapa: 'negociacion',
      etapaLabel: 'Negociación',
      probability: 70,
      assignedToName: 'Roberto Silva',
      facturacionEstimada: 110_000,
    },
    {
      id: 'mock-hot-3',
      urlSlug: 'bcp-ejecutivo',
      name: 'BCP Ejecutivo',
      etapa: 'licitacion_etapa_final',
      etapaLabel: 'Licitación Etapa Final',
      probability: 85,
      assignedToName: 'Carlos Mendoza',
      facturacionEstimada: 95_000,
    },
    {
      id: 'mock-hot-4',
      urlSlug: 'interbank-vip',
      name: 'Interbank VIP',
      etapa: 'licitacion',
      etapaLabel: 'Licitación',
      probability: 75,
      assignedToName: 'Carlos Mendoza',
      facturacionEstimada: 88_000,
    },
    {
      id: 'mock-hot-5',
      urlSlug: 'clinica-internacional',
      name: 'Clínica Internacional',
      etapa: 'cierre_ganado',
      etapaLabel: 'Cierre Ganado',
      probability: 90,
      assignedToName: 'Ana Torres',
      facturacionEstimada: 72_000,
    },
    {
      id: 'mock-hot-6',
      urlSlug: 'alicorp-ejecutivo',
      name: 'Alicorp Ejecutivo',
      etapa: 'negociacion',
      etapaLabel: 'Negociación',
      probability: 70,
      assignedToName: 'Ana Torres',
      facturacionEstimada: 68_000,
    },
    {
      id: 'mock-hot-7',
      urlSlug: 'hotel-belmond',
      name: 'Hotel Belmond',
      etapa: 'firma_contrato',
      etapaLabel: 'Firma de Contrato',
      probability: 95,
      assignedToName: 'María García',
      facturacionEstimada: 62_000,
    },
    {
      id: 'mock-hot-8',
      urlSlug: 'rcs-capital-humano',
      name: 'RCS CAPITAL HUMANO E.I.R.L.',
      etapa: 'negociacion',
      etapaLabel: 'Negociación',
      probability: 70,
      assignedToName: 'Maria Delgado',
      facturacionEstimada: 55_000,
    },
    {
      id: 'mock-hot-9',
      urlSlug: 'pucp-universitario',
      name: 'Plan Universitario PUCP',
      etapa: 'licitacion',
      etapaLabel: 'Licitación',
      probability: 75,
      assignedToName: 'María García',
      facturacionEstimada: 48_000,
    },
    {
      id: 'mock-hot-10',
      urlSlug: 'minera-los-andes',
      name: 'Minera Los Andes',
      etapa: 'cierre_ganado',
      etapaLabel: 'Cierre Ganado',
      probability: 90,
      assignedToName: 'Carlos Mendoza',
      facturacionEstimada: 42_000,
    },
    {
      id: 'mock-hot-11',
      urlSlug: 'embajada-espana',
      name: 'Embajada de España',
      etapa: 'firma_contrato',
      etapaLabel: 'Firma de Contrato',
      probability: 95,
      assignedToName: 'José Ramírez',
      facturacionEstimada: 38_000,
    },
    {
      id: 'mock-hot-12',
      urlSlug: 'solgas-sa',
      name: 'SOLGAS S.A.',
      etapa: 'negociacion',
      etapaLabel: 'Negociación',
      probability: 70,
      assignedToName: 'Monica Huertas',
      facturacionEstimada: 32_000,
    },
    {
      id: 'mock-hot-13',
      urlSlug: 'transportes-andinos',
      name: 'Transportes Andinos S.A.C.',
      etapa: 'licitacion_etapa_final',
      etapaLabel: 'Licitación Etapa Final',
      probability: 85,
      assignedToName: 'Roberto Silva',
      facturacionEstimada: 28_000,
    },
    {
      id: 'mock-hot-14',
      urlSlug: 'grupo-romero-logistica',
      name: 'Grupo Romero Logística',
      etapa: 'negociacion',
      etapaLabel: 'Negociación',
      probability: 70,
      assignedToName: 'Maria Delgado',
      facturacionEstimada: 24_000,
    },
    {
      id: 'mock-hot-15',
      urlSlug: 'backus-corporativo',
      name: 'Backus Corporativo',
      etapa: 'cierre_ganado',
      etapaLabel: 'Cierre Ganado',
      probability: 90,
      assignedToName: 'Ana Torres',
      facturacionEstimada: 18_500,
    },
  ],
};
